/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import Kontroler.GUIKontroler;
import Kontroler.Kontroler;
import domen.Agent;
import forme.klijent.DodajKlijentaPanel;
import forme.login.LoginForma;
import forme.partner.DodajPartneraPanel;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import sesija.Sesija;
/**
 *
 * @author Tami
 */
public class GlavnaForma extends javax.swing.JFrame{

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        this.setTitle("Turisticka Agencija");
        jmiPrijaviAgenta.setEnabled(false);
        jmiPocetna.setEnabled(false);
        jmiAranzmani.setEnabled(false);
        jmiUnosAranzmana.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnKreirajPartnera = new javax.swing.JButton();
        jbtnKreirajKlijenta = new javax.swing.JButton();
        jmbMeni = new javax.swing.JMenuBar();
        jmDatoteka = new javax.swing.JMenu();
        jmiPocetna = new javax.swing.JMenuItem();
        jmiPoslovniPartner = new javax.swing.JMenuItem();
        jmiKlijenti = new javax.swing.JMenuItem();
        jmiAranzmani = new javax.swing.JMenuItem();
        jmUnos = new javax.swing.JMenu();
        jmiUnosKlijenta = new javax.swing.JMenuItem();
        jmiUnosPoslovnogPartnera = new javax.swing.JMenuItem();
        jmiUnosAranzmana = new javax.swing.JMenuItem();
        jmAgent = new javax.swing.JMenu();
        jmiPrijaviAgenta = new javax.swing.JMenuItem();
        jmiOdjaviAgenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jbtnKreirajPartnera.setText("Brzo kreiranje partnera");
        jbtnKreirajPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajPartneraActionPerformed(evt);
            }
        });

        jbtnKreirajKlijenta.setText("Brzo kreiranje klijenta");
        jbtnKreirajKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajKlijentaActionPerformed(evt);
            }
        });

        jmDatoteka.setText("Datoteka");

        jmiPocetna.setText("Pocetna");
        jmDatoteka.add(jmiPocetna);

        jmiPoslovniPartner.setText("Poslovni partneri");
        jmiPoslovniPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPoslovniPartnerActionPerformed(evt);
            }
        });
        jmDatoteka.add(jmiPoslovniPartner);

        jmiKlijenti.setText("Klijenti");
        jmiKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKlijentiActionPerformed(evt);
            }
        });
        jmDatoteka.add(jmiKlijenti);

        jmiAranzmani.setText("Aranzmani");
        jmiAranzmani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAranzmaniActionPerformed(evt);
            }
        });
        jmDatoteka.add(jmiAranzmani);

        jmbMeni.add(jmDatoteka);

        jmUnos.setText("Unos");

        jmiUnosKlijenta.setText("Novi klijent");
        jmiUnosKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKlijentaActionPerformed(evt);
            }
        });
        jmUnos.add(jmiUnosKlijenta);

        jmiUnosPoslovnogPartnera.setText("Novi poslovni partner");
        jmiUnosPoslovnogPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosPoslovnogPartneraActionPerformed(evt);
            }
        });
        jmUnos.add(jmiUnosPoslovnogPartnera);

        jmiUnosAranzmana.setText("Novi aranzman");
        jmiUnosAranzmana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosAranzmanaActionPerformed(evt);
            }
        });
        jmUnos.add(jmiUnosAranzmana);

        jmbMeni.add(jmUnos);

        jmAgent.setText("Agent");

        jmiPrijaviAgenta.setText("Prijavi se");
        jmiPrijaviAgenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrijaviAgentaActionPerformed(evt);
            }
        });
        jmAgent.add(jmiPrijaviAgenta);

        jmiOdjaviAgenta.setText("Odjavi se");
        jmiOdjaviAgenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOdjaviAgentaActionPerformed(evt);
            }
        });
        jmAgent.add(jmiOdjaviAgenta);

        jmbMeni.add(jmAgent);

        setJMenuBar(jmbMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnKreirajPartnera)
                    .addComponent(jbtnKreirajKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbtnKreirajKlijenta)
                .addGap(18, 18, 18)
                .addComponent(jbtnKreirajPartnera)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPoslovniPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPoslovniPartnerActionPerformed
        GUIKontroler.invokePartnerForm();
        this.setVisible(false);
    }//GEN-LAST:event_jmiPoslovniPartnerActionPerformed

    private void jmiKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKlijentiActionPerformed
        GUIKontroler.invokeKlijentForm();
        this.setVisible(false);
    }//GEN-LAST:event_jmiKlijentiActionPerformed

    private void jmiAranzmaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAranzmaniActionPerformed
        
    }//GEN-LAST:event_jmiAranzmaniActionPerformed

    private void jmiUnosKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKlijentaActionPerformed
        DodajKlijentaPanel dkf = new DodajKlijentaPanel();
        JDialog dialog = new JDialog(this, "Unos Klijenta", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(dkf, BorderLayout.CENTER);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiUnosKlijentaActionPerformed

    private void jmiUnosPoslovnogPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosPoslovnogPartneraActionPerformed
        DodajPartneraPanel dpp = new DodajPartneraPanel();
        JDialog dialog = new JDialog(this, "Unos racuna", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(dpp, BorderLayout.CENTER);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiUnosPoslovnogPartneraActionPerformed

    private void jmiUnosAranzmanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosAranzmanaActionPerformed
       
    }//GEN-LAST:event_jmiUnosAranzmanaActionPerformed

    private void jmiPrijaviAgentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrijaviAgentaActionPerformed

    }//GEN-LAST:event_jmiPrijaviAgentaActionPerformed

    private void jbtnKreirajKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajKlijentaActionPerformed
        DodajKlijentaPanel dkf = new DodajKlijentaPanel();
        JDialog dialog = new JDialog(this, "Unos Klijenta", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(dkf, BorderLayout.CENTER);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jbtnKreirajKlijentaActionPerformed

    private void jbtnKreirajPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajPartneraActionPerformed
        DodajPartneraPanel dpp = new DodajPartneraPanel();
        JDialog dialog = new JDialog(this, "Unos partnera", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(dpp, BorderLayout.CENTER);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jbtnKreirajPartneraActionPerformed

    private void jmiOdjaviAgentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOdjaviAgentaActionPerformed
        try {
            Agent ulogovan = (Agent) Sesija.vratiInstancu().getMapa().get("agent");
            System.out.print("Ovog hocu da obrisem: "+ulogovan.toString());
            Object[] opcije = {"Da", "Ne"};
            String poruka = "Da li ste sigurni da zelite da se odjavite?";
            int izbor = JOptionPane.showOptionDialog(this, poruka, "Kraj rada", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcije, opcije[0]);
            if (izbor == 1) {
                return;
            }
            
            Kontroler.getInstance().izlogujSe(ulogovan);
            Sesija.vratiInstancu().getMapa().remove("agent", ulogovan);
            
            this.setVisible(false);
            this.dispose();
            
            LoginForma lf = new LoginForma();
            lf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiOdjaviAgentaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Agent ulogovan = (Agent) Sesija.vratiInstancu().getMapa().get("agent");
            System.out.print("Ovog hocu da obrisem: "+ulogovan.toString());
            Object[] opcije = {"Da", "Ne"};
            String poruka = "Da li ste sigurni da zelite da se odjavite?";
            int izbor = JOptionPane.showOptionDialog(this, poruka, "Kraj rada", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcije, opcije[0]);
            if (izbor == 1) {
                return;
            }
            
            Kontroler.getInstance().izlogujSe(ulogovan);
            Sesija.vratiInstancu().getMapa().remove("agent", ulogovan);
            
            this.setVisible(false);
            this.dispose();
            
            LoginForma lf = new LoginForma();
            lf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing
    
    public void disableFormu(){
        jmDatoteka.setEnabled(false);
        jmUnos.setEnabled(false);
        jmiOdjaviAgenta.setEnabled(true);
        jmiOdjaviAgenta.setEnabled(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnKreirajKlijenta;
    private javax.swing.JButton jbtnKreirajPartnera;
    private javax.swing.JMenu jmAgent;
    private javax.swing.JMenu jmDatoteka;
    private javax.swing.JMenu jmUnos;
    private javax.swing.JMenuBar jmbMeni;
    private javax.swing.JMenuItem jmiAranzmani;
    private javax.swing.JMenuItem jmiKlijenti;
    private javax.swing.JMenuItem jmiOdjaviAgenta;
    private javax.swing.JMenuItem jmiPocetna;
    private javax.swing.JMenuItem jmiPoslovniPartner;
    private javax.swing.JMenuItem jmiPrijaviAgenta;
    private javax.swing.JMenuItem jmiUnosAranzmana;
    private javax.swing.JMenuItem jmiUnosKlijenta;
    private javax.swing.JMenuItem jmiUnosPoslovnogPartnera;
    // End of variables declaration//GEN-END:variables

   
}
