/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.rezervacije;

import domen.Agent;
import domen.Aranzman;
import domen.Klijent;
import domen.Rezervacija;
import forme.klijent.DodajKlijentaPanel;
import java.awt.Color;
import java.awt.Window;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import komunikacija.Komunikacija;
import konstante.Konstante;
import sesija.Sesija;
import transfer.KlijentTransfer;
import transfer.ServerTransfer;

/**
 *
 * @author Tami
 */
public class DodajRezervacijuPanel extends javax.swing.JPanel {
    Rezervacija r;
    Klijent k;
    /**
     * Creates new form DodajRezervacijuPanel
     */
    public DodajRezervacijuPanel(Klijent prosledjen) {
        this.k=prosledjen;
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbAranzman = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtxtDatumRezervisanja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtRokPlacanja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtAvans = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtZaduzenje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Aranzman");

        jcbAranzman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbAranzman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbAranzmanMouseClicked(evt);
            }
        });
        jcbAranzman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAranzmanActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum");

        jLabel3.setText("Rok placanja");

        jLabel4.setText("Avans");

        jtxtAvans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtAvansMouseClicked(evt);
            }
        });
        jtxtAvans.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtxtAvansInputMethodTextChanged(evt);
            }
        });
        jtxtAvans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAvansActionPerformed(evt);
            }
        });

        jLabel5.setText("Zaduzenje");

        jButton1.setText("Kreiraj rezervaciju");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Otkazi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbAranzman, 0, 174, Short.MAX_VALUE)
                            .addComponent(jtxtDatumRezervisanja)
                            .addComponent(jtxtRokPlacanja)
                            .addComponent(jtxtAvans)
                            .addComponent(jtxtZaduzenje))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbAranzman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDatumRezervisanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtRokPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtAvans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtZaduzenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAranzmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAranzmanActionPerformed
        // nista se ne desava
    }//GEN-LAST:event_jcbAranzmanActionPerformed

    private void jtxtAvansInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtxtAvansInputMethodTextChanged
        //nista se ne desava
    }//GEN-LAST:event_jtxtAvansInputMethodTextChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!validirajFormu()) {
            JOptionPane.showMessageDialog(this, "Ne moze se kreirati rezervacija");
            return;
        }
        r = new Rezervacija();
        r.setKlijent(k);
        Aranzman ar = (Aranzman) jcbAranzman.getSelectedItem();
        Calendar cal = Calendar.getInstance();
        cal.setTime(ar.getDatumPolaska());
        cal.add(Calendar.DAY_OF_YEAR,-1);
        jtxtRokPlacanja.setText((new java.sql.Date((cal.getTime()).getTime())).toString());
        jtxtDatumRezervisanja.setText((new java.sql.Date((new Date()).getTime()).toString()));
        r.setAranzaman(ar);
        
        r.setDatum(new java.sql.Date((new Date()).getTime()));
        r.setRokPlacanja(new java.sql.Date((cal.getTime()).getTime()));
        
        try {
            Double avans = Double.parseDouble(jtxtAvans.getText().trim());
            r.setAvans(avans);
            r.setZaduzenje(r.getAranzaman().getCena()-r.getAvans());
            jtxtZaduzenje.setText(""+r.getZaduzenje());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unesite broj!");
        }
        
        r.setRezervacijaID(odrediId());
        r.setAgent((Agent) Sesija.vratiInstancu().getMapa().get("agent"));
        if (dodajRezervaciju(r)==true) {
            Window w = SwingUtilities.getWindowAncestor(this);
            w.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Neuspesno kreiranje rezervacije");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtAvansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAvansActionPerformed
        
    }//GEN-LAST:event_jtxtAvansActionPerformed

    private void jcbAranzmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbAranzmanMouseClicked
        
    }//GEN-LAST:event_jcbAranzmanMouseClicked

    private void jtxtAvansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtAvansMouseClicked
        if (jcbAranzman.getSelectedIndex()==-1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati aranzman prvo");
            return;
        }
       
    }//GEN-LAST:event_jtxtAvansMouseClicked

    private int odrediId() {
        try {
            KlijentTransfer kt = new KlijentTransfer();
            kt.setOperacija(Konstante.VRATI_REZERVACIJE);
            Komunikacija.getInstance().sendRequest(kt);
            ServerTransfer st = Komunikacija.getInstance().readResponse();
            List <Rezervacija> listrez = (List<Rezervacija>)st.getPodaci();
            int id=listrez.size()+1;
            return id;
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(DodajRezervacijuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jcbAranzman;
    private javax.swing.JTextField jtxtAvans;
    private javax.swing.JTextField jtxtDatumRezervisanja;
    private javax.swing.JTextField jtxtRokPlacanja;
    private javax.swing.JTextField jtxtZaduzenje;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jcbAranzman.removeAllItems();
        List<Aranzman> lista = vratiAranzmane();
        for (Aranzman ar : lista) {
            jcbAranzman.addItem(ar);
        }
        jcbAranzman.setSelectedIndex(-1);
        jtxtDatumRezervisanja.setEnabled(false);
        jtxtRokPlacanja.setEnabled(false);
        jtxtZaduzenje.setEnabled(false);
    }
    private List<Aranzman> vratiAranzmane(){
            List<Aranzman> listaar = new LinkedList<>();
        try {
            
            listaar = Kontroler.Kontroler.getInstance().getAranzmane();
        } catch (Exception ex) {
            Logger.getLogger(DodajRezervacijuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listaar;
                
    }

    private boolean dodajRezervaciju(Rezervacija r) {
        try {
            boolean kreiran= Kontroler.Kontroler.getInstance().kreirajRezervaciju(r);
            
            if (kreiran == true) {
                JOptionPane.showMessageDialog(this, "Uspesno kreirana rezervacija za klijenta: "+r.getKlijent().getIme()+" "+r.getKlijent().getPrezime());
                return true;
            }
        } catch (Exception ex) {
            Logger.getLogger(DodajRezervacijuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private boolean validirajFormu() {
        boolean valid =true;
        if (jtxtAvans.getText().isEmpty()) {
            jtxtAvans.setBorder(BorderFactory.createLineBorder(Color.RED));
            valid=false;
        }
        return valid;
    }
}
