/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.rezervacije;

import domen.Klijent;
import domen.Rezervacija;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import komunikacija.Komunikacija;
import konstante.Konstante;
import model.PrikaziRezTableModel;
import transfer.KlijentTransfer;
import transfer.ServerTransfer;

/**
 *
 * @author Tami
 */
public class PrikaziRezervacijeKlijentaPanel extends javax.swing.JPanel {
    Klijent k;
    /**
     * Creates new form PrikaziRezervacijeKlijentaPanel
     */
    public PrikaziRezervacijeKlijentaPanel(Klijent k) {
        initComponents();
        this.k=k;
        jtxtKlijent.setText(k.getIme()+" "+k.getPrezime());
        jtxtKlijent.setEditable(false);
        try {
            srediFormu();
        } catch (Exception ex) {
            Logger.getLogger(PrikaziRezervacijeKlijentaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtKlijent = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Rezervacije klijenta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtKlijent)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtKlijent;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws Exception {
        try {
            List<Rezervacija> klijentske;
            KlijentTransfer kt = new KlijentTransfer();
            kt.setOperacija(Konstante.VRATI_KLIJENTSKE_REZERVACIJE);
            kt.setParametar(k);
            Komunikacija.getInstance().sendRequest(kt);
            ServerTransfer st =  Komunikacija.getInstance().readResponse();
            if (st.getUspesnost()==Konstante.USPEH) {
                klijentske = (List<Rezervacija>) st.getPodaci();
                PrikaziRezTableModel model = new PrikaziRezTableModel(klijentske);
                jTable1.setModel(model);
            }else{
                Exception exi = st.getException();
                throw exi;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrikaziRezervacijeKlijentaPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PrikaziRezervacijeKlijentaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
