/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.aranzman;

import Kontroler.GUIKontroler;
import Kontroler.Kontroler;
import domen.Agent;
import domen.Aranzman;
import domen.Klijent;
import domen.PoslovniPartner;
import forme.GlavnaForma;
import forme.klijent.KlijentForma;
import forme.login.LoginForma;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Konstante;
import model.KlijentiTableModel;
import model.PrikaziAranzmanTableModel;
import sesija.Sesija;
import transfer.KlijentTransfer;
import transfer.ServerTransfer;

/**
 *
 * @author Tami
 */
public class AranzmanFrm extends javax.swing.JFrame {
    PoslovniPartner pp;
    /**
     * Creates new form AranzmanFrm
     */
    public AranzmanFrm(PoslovniPartner pp) {
        this.pp = pp;
        initComponents();
        try {
            srediFormu();
        } catch (Exception ex) {
            Logger.getLogger(AranzmanFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        jmiAranzmani.getComponent().setEnabled(false);
        jmiOdjaviAgenta.getComponent().setEnabled(false);
        jmiAgent.getComponent().setEnabled(false);   
    }

    public PoslovniPartner getPp() {
        return pp;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAranzmani = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtnDodajAranzman = new javax.swing.JButton();
        jbtnObrisiAranzman = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmDatoteka = new javax.swing.JMenu();
        jmiPocetna = new javax.swing.JMenuItem();
        jmiPoslovniPartner = new javax.swing.JMenuItem();
        jmiKlijenti = new javax.swing.JMenuItem();
        jmiAranzmani = new javax.swing.JMenuItem();
        jmUnos = new javax.swing.JMenu();
        jmiUnosKlijenta = new javax.swing.JMenuItem();
        jmiUnosPoslovnogPartnera = new javax.swing.JMenuItem();
        jmiUnosAranzmana = new javax.swing.JMenuItem();
        jmiAgent = new javax.swing.JMenu();
        jmiPrijaviKlijenta = new javax.swing.JMenuItem();
        jmiOdjaviAgenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtblAranzmani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblAranzmani);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Aranzmani");

        jbtnDodajAranzman.setText("Dodaj aranzman");
        jbtnDodajAranzman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajAranzmanActionPerformed(evt);
            }
        });

        jbtnObrisiAranzman.setText("Obrisi aranzman");
        jbtnObrisiAranzman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiAranzmanActionPerformed(evt);
            }
        });

        jmDatoteka.setText("Datoteka");

        jmiPocetna.setText("Pocetna");
        jmiPocetna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPocetnaActionPerformed(evt);
            }
        });
        jmDatoteka.add(jmiPocetna);

        jmiPoslovniPartner.setText("Poslovni partneri");
        jmiPoslovniPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPoslovniPartnerActionPerformed(evt);
            }
        });
        jmDatoteka.add(jmiPoslovniPartner);

        jmiKlijenti.setText("Klijenti");
        jmiKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKlijentiActionPerformed(evt);
            }
        });
        jmDatoteka.add(jmiKlijenti);

        jmiAranzmani.setText("Aranzmani");
        jmDatoteka.add(jmiAranzmani);

        jMenuBar1.add(jmDatoteka);

        jmUnos.setText("Unos");

        jmiUnosKlijenta.setText("Novi klijent");
        jmiUnosKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKlijentaActionPerformed(evt);
            }
        });
        jmUnos.add(jmiUnosKlijenta);

        jmiUnosPoslovnogPartnera.setText("Novi poslovni partner");
        jmiUnosPoslovnogPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosPoslovnogPartneraActionPerformed(evt);
            }
        });
        jmUnos.add(jmiUnosPoslovnogPartnera);

        jmiUnosAranzmana.setText("Novi aranzman");
        jmiUnosAranzmana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosAranzmanaActionPerformed(evt);
            }
        });
        jmUnos.add(jmiUnosAranzmana);

        jMenuBar1.add(jmUnos);

        jmiAgent.setText("Agent");

        jmiPrijaviKlijenta.setText("Prijavi se");
        jmiAgent.add(jmiPrijaviKlijenta);

        jmiOdjaviAgenta.setText("Odjavi se");
        jmiAgent.add(jmiOdjaviAgenta);

        jMenuBar1.add(jmiAgent);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnDodajAranzman)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnObrisiAranzman)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodajAranzman)
                    .addComponent(jbtnObrisiAranzman))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKlijentiActionPerformed
        GUIKontroler.invokeKlijentForm();
        this.setVisible(false);
    }//GEN-LAST:event_jmiKlijentiActionPerformed

    private void jmiPocetnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPocetnaActionPerformed
        GUIKontroler.invokeMainForm();
        this.setVisible(false);
    }//GEN-LAST:event_jmiPocetnaActionPerformed

    private void jmiPoslovniPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPoslovniPartnerActionPerformed
        GUIKontroler.invokePartnerForm();
        this.setVisible(false);
    }//GEN-LAST:event_jmiPoslovniPartnerActionPerformed

    private void jmiUnosKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKlijentaActionPerformed
    }//GEN-LAST:event_jmiUnosKlijentaActionPerformed

    private void jmiUnosPoslovnogPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosPoslovnogPartneraActionPerformed
    }//GEN-LAST:event_jmiUnosPoslovnogPartneraActionPerformed

    private void jmiUnosAranzmanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosAranzmanaActionPerformed
    }//GEN-LAST:event_jmiUnosAranzmanaActionPerformed

    private void jbtnDodajAranzmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajAranzmanActionPerformed
        DodajAranzmanPanel dap = new DodajAranzmanPanel(this.getPp());
        JDialog dialog = new JDialog(this, "Novi Aranzman", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(dap, BorderLayout.CENTER);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jbtnDodajAranzmanActionPerformed

    private void jbtnObrisiAranzmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiAranzmanActionPerformed
        try {
            
            PrikaziAranzmanTableModel ktm = (PrikaziAranzmanTableModel) jtblAranzmani.getModel();
            if (jtblAranzmani.getSelectedRow()==-1) {
                JOptionPane.showMessageDialog(this, "Morate selektovati aranzman!");
                return;
            }
            
            KlijentTransfer kt = new KlijentTransfer();
            kt.setOperacija(Konstante.OBRISI_ARANZMAN);
            Aranzman a = ktm.getLista().get(jtblAranzmani.getSelectedRow());
            System.out.println(a.toString());
            kt.setParametar(a);
            Komunikacija.getInstance().sendRequest(kt);
            ServerTransfer st = Komunikacija.getInstance().readResponse();
            if (st.getUspesnost()==Konstante.USPEH) {
                JOptionPane.showMessageDialog(this, "Aranzman uspesno obrisan");
                ktm.getLista().remove(a);
                ktm.fireTableDataChanged();
            }
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(KlijentForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnObrisiAranzmanActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Agent ulogovan = (Agent) Sesija.vratiInstancu().getMapa().get("agent");
            System.out.print("Ovog hocu da obrisem: "+ulogovan.toString());
            
            Kontroler.getInstance().izlogujSe(ulogovan);
            Sesija.vratiInstancu().getMapa().remove("agent", ulogovan);
            
            this.setVisible(false);
            this.dispose();
            
            LoginForma lf = new LoginForma();
            lf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajAranzman;
    private javax.swing.JButton jbtnObrisiAranzman;
    private javax.swing.JMenu jmDatoteka;
    private javax.swing.JMenu jmUnos;
    private javax.swing.JMenu jmiAgent;
    private javax.swing.JMenuItem jmiAranzmani;
    private javax.swing.JMenuItem jmiKlijenti;
    private javax.swing.JMenuItem jmiOdjaviAgenta;
    private javax.swing.JMenuItem jmiPocetna;
    private javax.swing.JMenuItem jmiPoslovniPartner;
    private javax.swing.JMenuItem jmiPrijaviKlijenta;
    private javax.swing.JMenuItem jmiUnosAranzmana;
    private javax.swing.JMenuItem jmiUnosKlijenta;
    private javax.swing.JMenuItem jmiUnosPoslovnogPartnera;
    private javax.swing.JTable jtblAranzmani;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws Exception {
        try {
            KlijentTransfer kt = new KlijentTransfer();
            kt.setOperacija(Konstante.VRATI_PARTNERSKE_ARANZMANE);
            kt.setParametar(pp);
            Komunikacija.getInstance().sendRequest(kt);
            ServerTransfer st = Komunikacija.getInstance().readResponse();
            if (st.getUspesnost()==Konstante.USPEH) {
                List<Aranzman> ar = (List<Aranzman>)st.getPodaci();
                PrikaziAranzmanTableModel ptm = new PrikaziAranzmanTableModel(ar);
                jtblAranzmani.setModel(ptm);
            
            }else{
                Exception exi = st.getException();
                throw exi;
            }
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(AranzmanFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
}
