/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.partner;

import Kontroler.Kontroler;
import domen.Aranzman;
import domen.Mesto;
import domen.PoslovniPartner;
import domen.StavkaAranzmana;
import java.awt.Color;
import java.awt.Window;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import model.StavkeAranzmanaTableModel;

/**
 *
 * @author Tami
 */
public class DodajPartneraPanel extends javax.swing.JPanel {
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    PoslovniPartner pp;
    List<Aranzman> aranzmani;
    Aranzman ar;
    List<Integer> tipovi;
    /**
     * Creates new form DodajPartneraPanel
     */
    public DodajPartneraPanel() {
        initComponents();
        
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jtxtUnosUlica = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtUnosAdresaBroj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListaAranzmana = new javax.swing.JTable();
        jtxtUnosPartnerID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtUnosPIB = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jbtnDodajAranzman = new javax.swing.JButton();
        jtxtUnosMaticni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnSacuvajPartnera = new javax.swing.JButton();
        jtxtUnosNaziv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtUnosTip = new javax.swing.JTextField();
        jcmbUnosPartnerMesto = new javax.swing.JComboBox();
        jbtnDodajStavku = new javax.swing.JButton();
        jbtnObrisiStavku = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jtxtAranzmanID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtxtDatumdo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtDestinacija = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtxtAranzmanCena = new javax.swing.JTextField();
        jtxtDatumOd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnSacuvajSve = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtZiroracun = new javax.swing.JTextField();

        jLabel12.setText("Ulica");

        jLabel14.setText("Broj");

        jLabel10.setText("Adresa:");

        jLabel2.setText("PoslovniPartnerID:");

        jLabel11.setText("Mesto");

        jtblListaAranzmana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jtblListaAranzmana);

        jtxtUnosPartnerID.setEditable(false);

        jLabel3.setText("PIB");

        jLabel1.setText("Aranzmani");

        jLabel4.setText("Maticni broj");

        jbtnDodajAranzman.setText("Dodaj aranzman");
        jbtnDodajAranzman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajAranzmanActionPerformed(evt);
            }
        });

        jtxtUnosMaticni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUnosMaticniActionPerformed(evt);
            }
        });

        jLabel5.setText("Naziv");

        jbtnSacuvajPartnera.setText("Sacuvaj partnera");
        jbtnSacuvajPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajPartneraActionPerformed(evt);
            }
        });

        jLabel6.setText("Tip Poslovnog Partnera");

        jcmbUnosPartnerMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnDodajStavku.setText("+");
        jbtnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajStavkuActionPerformed(evt);
            }
        });

        jbtnObrisiStavku.setText("-");
        jbtnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiStavkuActionPerformed(evt);
            }
        });

        jLabel13.setText("AranzmanID: ");

        jtxtAranzmanID.setEditable(false);

        jLabel15.setText("Naziv");

        jLabel16.setText("Datum od");

        jLabel17.setText("Datum do");

        jtxtDatumdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDatumdoActionPerformed(evt);
            }
        });

        jLabel18.setText("Destinacija");

        jLabel19.setText("Cena");

        jLabel20.setText("Stavke aranzmana");

        jbtnSacuvajSve.setText("Sacuvaj");
        jbtnSacuvajSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajSveActionPerformed(evt);
            }
        });

        jLabel7.setText("Ziro racun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtUnosNaziv)
                                        .addComponent(jtxtUnosMaticni)
                                        .addComponent(jtxtUnosPIB)
                                        .addComponent(jtxtUnosTip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(jtxtUnosPartnerID, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel13))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel16))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel19))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtAranzmanID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtAranzmanCena, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtDatumdo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(42, 42, 42)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtnSacuvajPartnera)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnDodajStavku)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtnObrisiStavku))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addComponent(jbtnSacuvajSve)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(59, 59, 59)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel14)
                                                            .addComponent(jLabel12))))
                                                .addComponent(jLabel10))
                                            .addGap(50, 50, 50))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(90, 90, 90)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtUnosUlica)
                                        .addComponent(jcmbUnosPartnerMesto, 0, 127, Short.MAX_VALUE)
                                        .addComponent(jtxtUnosAdresaBroj, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(jtxtZiroracun)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnDodajAranzman, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtUnosPartnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtUnosPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtUnosMaticni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jcmbUnosPartnerMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jtxtUnosUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtUnosAdresaBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtUnosNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel5)
                    .addComponent(jtxtZiroracun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtUnosTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSacuvajPartnera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnDodajStavku)
                            .addComponent(jbtnObrisiStavku)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtAranzmanID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtAranzmanCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDatumdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnDodajAranzman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSacuvajSve)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajAranzmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajAranzmanActionPerformed
        try {                                                  
            StavkeAranzmanaTableModel satm = (StavkeAranzmanaTableModel) jtblListaAranzmana.getModel();
            if (satm.getRowCount()<1) {
                JOptionPane.showMessageDialog(this, "Morate imati najmanje jednu stavku");
                return;
            }
            if (!validirajFormuAranzman()) {
                JOptionPane.showMessageDialog(this, "Unete vrednosti nisu u dobrom formatu");
                return;
            }
            Double cena = Double.parseDouble(jtxtAranzmanCena.getText());
            String naziv = jtxtNaziv.getText();
            String destinacija = jtxtDestinacija.getText();
            ar.setCena(cena);
            ar.setNaziv(naziv);
            ar.setDestinacija(destinacija);
            try {
                Date datumod = sdf.parse(jtxtDatumOd.getText());
                Date datumdo = sdf.parse(jtxtDatumdo.getText());
                ar.setDatumPolaska(new java.sql.Date((datumod.getTime())));
                ar.setDatumPovratka(new java.sql.Date((datumdo.getTime())));
            } catch (ParseException ex) {
                Logger.getLogger(DodajPartneraPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (Kontroler.getInstance().kreirajAranzman(ar)) {
                for (StavkaAranzmana stavka : satm.getAraz().getListaStavki()) {
                    stavka.setRbStavke(ar.getAranzmanID()*10+satm.getAraz().getListaStavki().indexOf(stavka));
                    Kontroler.getInstance().kreirajStavkuAranzmana(stavka);
                        
                    
                }
                aranzmani.add(ar);
                resetujAranzmanFormu();
            }
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(DodajPartneraPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jbtnDodajAranzmanActionPerformed

    private void jtxtDatumdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDatumdoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDatumdoActionPerformed

    private void jbtnSacuvajPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajPartneraActionPerformed
        
            if (!validirajFormuPartner()) {
                JOptionPane.showMessageDialog(this, "Partnera nije moguce sacuvati!");
                return;
            }
            Integer pib = Integer.parseInt(jtxtUnosPIB.getText());
            Integer maticni = Integer.parseInt(jtxtUnosMaticni.getText());
            String naziv = jtxtUnosNaziv.getText();
            Integer tip = Integer.parseInt(jtxtUnosTip.getText());
            Mesto mesto =(Mesto) jcmbUnosPartnerMesto.getSelectedItem();
            String ulica = jtxtUnosUlica.getText();
            String broj = jtxtUnosAdresaBroj.getText();
            String ziro = jtxtZiroracun.getText();
            pp.setBroj(broj);
            pp.setMaticniBroj(maticni);
            pp.setMesto(mesto);
            pp.setNaziv(naziv);
            pp.setPib(pib);
            pp.setTipPoslovnogPartnera(tip);
            pp.setUlica(ulica);
            pp.setZiroRacun(ziro);
            try {
                Kontroler.getInstance().kreirajPartnera(pp);
                JOptionPane.showMessageDialog(this, "Partner: "+naziv+" uspesno kreiran!");
                disableDodajPartnera(false);
                disableEnableAranzman(true);
                
                jtxtAranzmanID.setText(""+ar.getAranzmanID());
                jbtnSacuvajSve.setEnabled(true);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Nije u redu!","Greska!",JOptionPane.ERROR_MESSAGE);
                
            }
        
    }//GEN-LAST:event_jbtnSacuvajPartneraActionPerformed

    private void jbtnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajStavkuActionPerformed
        StavkaAranzmana nova = new StavkaAranzmana();
        ar.dodajStavku(nova);
        nova.setAranzman(ar);
        
        StavkeAranzmanaTableModel atm = (StavkeAranzmanaTableModel) jtblListaAranzmana.getModel();
        atm.fireTableDataChanged();
    }//GEN-LAST:event_jbtnDodajStavkuActionPerformed

    private void jbtnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiStavkuActionPerformed
        int red = jtblListaAranzmana.getSelectedRow();
        if (red >= 0) {
            ar.getListaStavki().remove(red);
            
            StavkeAranzmanaTableModel model = (StavkeAranzmanaTableModel) jtblListaAranzmana.getModel();
            model.fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Morate odabrati stavku!");
            
        }
    }//GEN-LAST:event_jbtnObrisiStavkuActionPerformed

    private void jtxtUnosMaticniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUnosMaticniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUnosMaticniActionPerformed

    private void jbtnSacuvajSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajSveActionPerformed
        if (aranzmani.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Partner: "+pp.getNaziv()+" je sacuvan. Nema unesenih aranzmana!");
            Window w = SwingUtilities.getWindowAncestor(this);
            w.setVisible(false);
        }
        JOptionPane.showMessageDialog(this, "Uspesno sacuvano: "+aranzmani.size() +" aranzmana.");
        Window w = SwingUtilities.getWindowAncestor(this);
                    w.setVisible(false);
    }//GEN-LAST:event_jbtnSacuvajSveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnDodajAranzman;
    private javax.swing.JButton jbtnDodajStavku;
    private javax.swing.JButton jbtnObrisiStavku;
    private javax.swing.JButton jbtnSacuvajPartnera;
    private javax.swing.JButton jbtnSacuvajSve;
    private javax.swing.JComboBox jcmbUnosPartnerMesto;
    private javax.swing.JTable jtblListaAranzmana;
    private javax.swing.JTextField jtxtAranzmanCena;
    private javax.swing.JTextField jtxtAranzmanID;
    private javax.swing.JTextField jtxtDatumOd;
    private javax.swing.JTextField jtxtDatumdo;
    private javax.swing.JTextField jtxtDestinacija;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtUnosAdresaBroj;
    private javax.swing.JTextField jtxtUnosMaticni;
    private javax.swing.JTextField jtxtUnosNaziv;
    private javax.swing.JTextField jtxtUnosPIB;
    private javax.swing.JTextField jtxtUnosPartnerID;
    private javax.swing.JTextField jtxtUnosTip;
    private javax.swing.JTextField jtxtUnosUlica;
    private javax.swing.JTextField jtxtZiroracun;
    // End of variables declaration//GEN-END:variables
    private boolean validirajFormuAranzman(){
        vratiIviceForme();
        boolean valid = true;
        List<JTextField> textFields = new LinkedList<>();
        textFields.add(jtxtAranzmanCena);
        textFields.add(jtxtDatumOd);
        textFields.add(jtxtDatumdo);
        textFields.add(jtxtDestinacija);
        textFields.add(jtxtNaziv);
        for (JTextField field : textFields) {
            if (field.getText().isEmpty()) {
                valid=false;
                field.setBorder(BorderFactory.createLineBorder(Color.RED));
            }
        }
        
        try {
            if (Double.parseDouble(jtxtAranzmanCena.getText().trim())<1) {
                
                jtxtAranzmanCena.setText("Cena manja od 1");
                jtxtAranzmanCena.setBorder(BorderFactory.createLineBorder(Color.RED));
                valid=false;
            }

        } catch (Exception e) {
            valid = false;
            jtxtAranzmanCena.setText("Format nije dobar");
            jtxtAranzmanCena.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        
        String dateod = jtxtDatumOd.getText();
        try {
            Date datod = sdf.parse(dateod);
            if (datod.before(new Date())) {
                valid = false;
                jtxtDatumOd.setBorder(BorderFactory.createLineBorder(Color.RED));
                jtxtDatumOd.setText("Ne moze pre danasnjeg datuma!");
            }
            
        } catch (ParseException ex) {
            jtxtDatumOd.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtDatumOd.setText("dd/MM/yyyy");
            
        }
        String datedo = jtxtDatumdo.getText();
        try {
            Date datdo = sdf.parse(datedo);
            if (datdo.before(new Date())) {
                valid = false;
                jtxtDatumOd.setBorder(BorderFactory.createLineBorder(Color.RED));
                jtxtDatumOd.setText("Ne moze pre danasnjeg datuma!");
            }
            
            
        } catch (ParseException ex) {
            jtxtDatumdo.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtDatumdo.setText("dd/MM/yyyy");
            valid = false;
        }
        
        return valid;
        
    }
    private boolean validirajFormuPartner(){
        vratiIviceForme();
        boolean valid =true;
        List<JTextField> textFields = new LinkedList<>();
        textFields.add(jtxtUnosAdresaBroj);
        textFields.add(jtxtUnosMaticni);
        textFields.add(jtxtUnosNaziv);
        textFields.add(jtxtUnosPIB);
        textFields.add(jtxtUnosTip);
        textFields.add(jtxtUnosUlica);
        for (JTextField field : textFields) {
            if (field.getText().isEmpty()) {
                valid=false;
                field.setBorder(BorderFactory.createLineBorder(Color.RED));
            }
        }
        try {
            
            if (!tipovi.contains(Integer.parseInt(jtxtUnosTip.getText()))) {
                jtxtUnosTip.setBorder(BorderFactory.createLineBorder(Color.RED));
                jtxtUnosTip.setText("1 za smestaj, 2 za prevoz");
                valid=false;
            }
        } catch (Exception e) {
            jtxtUnosTip.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtUnosTip.setText("1 za smestaj, 2 za prevoz");
            valid=false;
        }
        try {
            if (Integer.parseInt(jtxtUnosMaticni.getText().trim())<10000000 || Integer.parseInt(jtxtUnosMaticni.getText().trim())>99999999) {
                jtxtUnosMaticni.setBorder(BorderFactory.createLineBorder(Color.RED));
                jtxtUnosMaticni.setText("Uneti 8 cifara");
                valid=false;
            }
        } catch (Exception e) {
                jtxtUnosMaticni.setBorder(BorderFactory.createLineBorder(Color.RED));
                jtxtUnosMaticni.setText("greska u formatu");
                System.out.println(e.getMessage());
                valid=false;
        }
        try {
            if (Integer.parseInt(jtxtUnosPIB.getText().trim())<100000000 || Integer.parseInt(jtxtUnosPIB.getText().trim())>999999999) {
                jtxtUnosPIB.setBorder(BorderFactory.createLineBorder(Color.RED));
                jtxtUnosPIB.setText("Uneti 9 cifara");
                valid=false;
            }
        } catch (Exception e) {
                jtxtUnosPIB.setBorder(BorderFactory.createLineBorder(Color.RED));
                jtxtUnosPIB.setText("greska u formatu");
                System.out.println(e.getMessage());
                valid=false;
        }
        if (jcmbUnosPartnerMesto.getSelectedIndex()==-1) {
            valid=false;
            jcmbUnosPartnerMesto.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        
        return valid;
        
    }
    private void srediFormu() {
        srediComboMesto();
        tipovi = new LinkedList<>();
        tipovi.add(1);
        tipovi.add(2);
        
        ar = new Aranzman();
        ar.setAranzmanID(postaviAranzmanID(vratiAranzmane()));
        aranzmani = new LinkedList<>();
        pp = new PoslovniPartner();
        pp.setPoslovniPartnerID(postaviPPID(vratiPartnere()));
        StavkeAranzmanaTableModel satm = new StavkeAranzmanaTableModel();
        satm.setAraz(ar);
        jcmbUnosPartnerMesto.setSelectedIndex(-1);
        jtblListaAranzmana.setModel(satm);
        jtxtUnosPartnerID.setText(pp.getPoslovniPartnerID()+"");
        jtxtUnosPartnerID.setEditable(false);
        jbtnSacuvajSve.setEnabled(false);
        disableEnableAranzman(false);
        disableDodajPartnera(true);
        
    }
     private void srediComboMesto() {
        jcmbUnosPartnerMesto.removeAllItems();
        List<Mesto> mesta = vratiMesta();
        for (Mesto m : mesta) {
            jcmbUnosPartnerMesto.addItem(m);
        }
        jcmbUnosPartnerMesto.setSelectedItem(-1);
    }

    private List<Mesto> vratiMesta() {
        try {
            List<Mesto> lista =Kontroler.getInstance().getMesta();
            return lista;
        } catch (Exception ex) {
            Logger.getLogger(PartnerFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    private List<StavkaAranzmana> vratiStavke(){
        List<StavkaAranzmana> lista=  new LinkedList<>();
        try {
            lista = Kontroler.getInstance().getSveStavke();
            
        } catch (Exception ex) {
            Logger.getLogger(DodajPartneraPanel.class.getName()).log(Level.SEVERE, null, ex);
        }return lista;
    }
    
    private List<PoslovniPartner> vratiPartnere(){
        List<PoslovniPartner> lista = new LinkedList<>();
        try {
            lista = Kontroler.getInstance().getPoslovnePartnere();
        } catch (Exception ex) {
            Logger.getLogger(DodajPartneraPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    
    private List<Aranzman> vratiAranzmane(){
        List<Aranzman> lista = new LinkedList<>();
        try {
            lista = Kontroler.getInstance().getAranzmane();
            return lista;
        } catch (Exception ex) {
            Logger.getLogger(DodajPartneraPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    
    private int postaviPPID(List<PoslovniPartner> pplista){
        int ppid = pplista.get(pplista.size()-1).getPoslovniPartnerID()+1;
        return ppid;
    }
    private int postaviAranzmanID(List<Aranzman> arlista){
        int arid = arlista.get(arlista.size()-1).getAranzmanID()+1;
        return arid;
    }
    private void disableEnableAranzman(boolean disable){
        jtxtNaziv.setEnabled(disable);
        jtxtDestinacija.setEnabled(disable);
        jtxtAranzmanCena.setEnabled(disable);
        jtxtDatumOd.setEnabled(disable);
        jtxtDatumdo.setEnabled(disable);
        jbtnDodajAranzman.setEnabled(disable);
        jbtnDodajStavku.setEnabled(disable);
        jbtnObrisiStavku.setEnabled(disable);
        
    }
    private void disableDodajPartnera(boolean disable){
        jtxtUnosAdresaBroj.setEnabled(disable);
        jtxtUnosMaticni.setEnabled(disable);
        jtxtUnosNaziv.setEnabled(disable);
        jtxtUnosPIB.setEnabled(disable);
        jtxtUnosTip.setEnabled(disable);
        jtxtUnosUlica.setEnabled(disable);
        jcmbUnosPartnerMesto.setEnabled(disable);
        jbtnSacuvajPartnera.setEnabled(disable);
        jtxtZiroracun.setEnabled(disable);
    }
    
    private void vratiIviceForme(){
        List<JTextField> textFields = new LinkedList<>();
        textFields.add(jtxtUnosAdresaBroj);
        textFields.add(jtxtUnosMaticni);
        textFields.add(jtxtUnosNaziv);
        textFields.add(jtxtUnosPIB);
        textFields.add(jtxtUnosTip);
        textFields.add(jtxtUnosUlica);
        textFields.add(jtxtAranzmanCena);
        textFields.add(jtxtDatumOd);
        textFields.add(jtxtDatumdo);
        textFields.add(jtxtNaziv);
        textFields.add(jtxtDestinacija);
        for (JTextField field : textFields) {
            field.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }
        jcmbUnosPartnerMesto.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        
    }
    private void resetujAranzmanFormu(){
        ar = new Aranzman();
        ar.setAranzmanID(aranzmani.get(aranzmani.size()-1).getAranzmanID()+1);
        jtxtAranzmanID.setText(""+ar.getAranzmanID());
        jtxtAranzmanCena.setText("");
        jtxtNaziv.setText("");
        jtxtDatumOd.setText("");
        jtxtDatumdo.setText("");
        jtxtDestinacija.setText("");
        jtblListaAranzmana.setModel(new StavkeAranzmanaTableModel());
    }
}
